version: '3.9'

services:
  golang_app:
    container_name: golang_app
    image: transaction-processor-api:latest
    build: .
    environment:
      DATABASE_DSN: ""
      MAILTRAP_HOST: ""
      MAILTRAP_TOKEN: ""
      MAILTRAP_FROM_EMAIL: ""
      TRANSACTIONS_FILE_PATH: ""
      EMAIL_LOGO_URL: ""
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/local/volume:/var/lib/postgresql/data